<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE EPG [
  <!ELEMENT EPG (Configurations, EpgStates)>
  <!ATTLIST EPG version CDATA #IMPLIED>
  <!ELEMENT Configurations (StateTransisionTimeout,MenuTransisionTimeout, StateTransisionAnimationDuraiton, MenuTransisionAnimationDuraiton,RetryTimeout,RetriesCount)>
  <!ELEMENT StateTransisionTimeout EMPTY>
  <!ELEMENT MenuTransisionTimeout EMPTY>
  <!ELEMENT StateTransisionAnimationDuraiton EMPTY>
  <!ELEMENT MenuTransisionAnimationDuraiton EMPTY>
  <!ELEMENT RetryTimeout EMPTY>
  <!ELEMENT RetriesCount (#PCDATA)>
  <!ATTLIST StateTransisionTimeout time CDATA #REQUIRED>
  <!ATTLIST MenuTransisionTimeout time CDATA #REQUIRED>
  <!ATTLIST StateTransisionAnimationDuraiton time CDATA #REQUIRED>
  <!ATTLIST MenuTransisionAnimationDuraiton time CDATA #REQUIRED>
  <!ATTLIST RetryTimeout time CDATA #REQUIRED>
  <!ELEMENT EpgStates (State)*>
  <!ELEMENT State (ActivationCriterias,DirectDestinations?, Menu?, Menus?) >
  <!ATTLIST State name CDATA #REQUIRED>
  <!ATTLIST State extraAnimationDuration CDATA #IMPLIED>
  <!ATTLIST State xsi:type (DALSimpleMenuState|DALComplexMenuState) #IMPLIED>
  <!ELEMENT ActivationCriterias (ActivationCriteria)*>
  <!ELEMENT ActivationCriteria EMPTY>
  <!ATTLIST ActivationCriteria key CDATA #REQUIRED>
  <!ATTLIST ActivationCriteria value CDATA #REQUIRED>
  <!ELEMENT DirectDestinations (DirectDestination)*>
  <!ELEMENT DirectDestination (IrKey?, Delay?)>
  <!ATTLIST DirectDestination name CDATA #REQUIRED>
  <!ELEMENT IrKey EMPTY>
  <!ATTLIST IrKey name CDATA #IMPLIED>
  <!ATTLIST IrKey pressDuration CDATA #IMPLIED>
  <!ELEMENT Delay EMPTY>
  <!ATTLIST Delay time CDATA #IMPLIED>
  <!ELEMENT Menu (Items)>
  <!ELEMENT Items (Item)*>
  <!ELEMENT Item EMPTY>
  <!ATTLIST Item name CDATA #REQUIRED>
  <!ATTLIST Item dictionaryKey CDATA #IMPLIED>
  <!ATTLIST Item destination CDATA #IMPLIED>
  <!ELEMENT Menus ANY>

]>

<EPG xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" version="1.6">
  <Configurations>
    <StateTransisionTimeout time="30" />
    <MenuTransisionTimeout time="10" />
    <StateTransisionAnimationDuraiton time="5" />
    <MenuTransisionAnimationDuraiton time="2" />
    <RetryTimeout time="600"/>
    <RetriesCount>3</RetriesCount>
  </Configurations>
  <EpgStates>

    <!--Dummy state representing the 'out of sync' state-->
    <State name="UNKNOWN">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="unknownState" />
      </ActivationCriterias>
      <DirectDestinations />
    </State>

    <!--Live viewing-->
    <State name="LIVE">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="IdleState" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
        <DirectDestination name="CHANNEL BAR">
          <IrKey name="RETOUR" />
        </DirectDestination>
        <DirectDestination name="ACTION BAR">
          <IrKey name="SELECT" />
        </DirectDestination>
        <DirectDestination name="TRICKMODE BAR">
          <IrKey name="PAUSE" />
        </DirectDestination>
      </DirectDestinations>
    </State>

    <!--Playback viewing-->
    <State name="PLAYBACK">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="PlayBackIdleState" />
        <ActivationCriteria key="scrnCtrl" value="ScreenCntrlr" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
        <DirectDestination name="CHANNEL BAR">
          <IrKey name="RETOUR" />
        </DirectDestination>
        <DirectDestination name="ACTION BAR">
          <IrKey name="SELECT" />
        </DirectDestination>
        <DirectDestination name="TRICKMODE BAR">
          <IrKey name="PAUSE" />
        </DirectDestination>
      </DirectDestinations>
    </State>

    <!--Channel Bar-->
    <State xsi:type="DALSimpleMenuState" name="CHANNEL BAR">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="ChBarState" />
        <ActivationCriteria key="scrnCtrl" value="ChBarScreenCntrlr" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU" />
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="RightLeft" type="Circular" selectionIdentifier="title">
        <Items>
          <Item name="NOW" dictionaryKey="DIC_NOW" destination="LIVE"/>
          <Item name="NEXT" dictionaryKey="DIC_NEXT" destination="ACTION BAR"/>
        </Items>
      </Menu>
    </State>

    <!--Zap Channel Bar (loads after 'back to live' from the player)-->
    <State  xsi:type="DALSimpleMenuState" name="ZAP CHANNEL BAR">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="ZapTransState" />
        <ActivationCriteria key="scrnCtrl" value="ChBarScreenCntrlr" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU" />
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="RightLeft" type="Circular" selectionIdentifier="title">
        <Items>
          <Item name="NOW" dictionaryKey="DIC_NOW" destination="LIVE"/>
        </Items>
      </Menu>
    </State>

    <!--Action Bar -> Record Event, depends on weather the event is part of a series. if not, only the top 2 appear. if hes, the 3 lower items appear-->
    <State  xsi:type="DALSimpleMenuState" name="EVENT RECORDING">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="EventRecordingState" />
        <ActivationCriteria key="scrnCtrl" value="ActionsMenuScrnCtrlr" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU" />
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
          <Item name="CONFIRM" dictionaryKey="DIC_ACTION_LIST_RECORD_EVENT" destination="LIVE"/>
          <Item name="MODIFY" dictionaryKey="DIC_LIBRARY_MODIFY_PARAMS" destination="LIVE"/>
          <Item name="RECORD THIS EPISODE" dictionaryKey="DIC_ACTION_LIST_RECORD_SERIE_EVENT" destination="LIVE"/>
          <Item name="RECORD ALL EPISODES" dictionaryKey="DIC_ACTION_LIST_RECORD_SERIE" destination="LIVE"/>
        </Items>
      </Menu>
    </State>

    <!--Action Bar-->
    <State  xsi:type="DALSimpleMenuState" name="ACTION BAR">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="ProgramActionState" />
        <ActivationCriteria key="scrnCtrl" value="ActionsMenuScrnCtrlr" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU" />
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
          <Item name="SEARCH" dictionaryKey="DIC_PROG_ACTION_SEARCH" destination=""/>
          <Item name="A//V SETTINGS" dictionaryKey="DIC_PROG_ACTION_FORMAT" destination="A//V SETTINGS"/>
          <Item name="MORE LIKE THIS" dictionaryKey="DIC_STORE_RELATED" destination="MORE LIKE THIS"/>
          <Item name="INFO" dictionaryKey="DIC_PROG_ACTION_SUMMARY" destination="INFO"/>
          <Item name="PAUSE" dictionaryKey="DIC_PROG_ACTION_PAUSE" destination="TRICKMODE BAR"/>
          <Item name="RECORD" dictionaryKey="DIC_PROG_ACTION_RECORD"  destination="EVENT RECORDING"/>
          <Item name="STOP RECORDING" dictionaryKey="DIC_PROG_ACTION_CANCEL_RECORD"  destination=""/>
          <Item name="PLAY" dictionaryKey="DIC_PROG_ACTION_PLAY" destination=""/>
          <Item name="ADD REMINDER" dictionaryKey="DIC_PROG_ACTION_ADDTOFAVORITES" destination="CONFIRMATION"/>
          <Item name="MAKE FAVOURITE" dictionaryKey="DIC_PROG_ACTION_ADDTOFAVORITES" destination="CONFIRMATION"/>
          <Item name="BACK TO LIVE TV" dictionaryKey="DIC_PROG_ACTION_BACK_TO_LIVE" destination=""/>
        </Items>
      </Menu>
    </State>

    <!--ACTION BAR -> MORE LIKE THIS-->
    <State name="MORE LIKE THIS">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="ContentListingState" />
        <ActivationCriteria key="scrnCtrl" value="ContentListingScreenCntrlr" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
        <DirectDestination name="ACTION BAR">
          <IrKey name="RETOUR" />
        </DirectDestination>
      </DirectDestinations>
    </State>
    
    <!--ACTION BAR -> INFO-->    
    <State name="INFO">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="SummaryState" />
        <ActivationCriteria key="scrnCtrl" value="ActionsMenuScrnCtrlr" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
        <DirectDestination name="ACTION BAR">
          <IrKey name="RETOUR" />
        </DirectDestination>      
      </DirectDestinations>
    </State>

    <!--ACTION BAR -> A/V SETTINGS-->
    <State  xsi:type="DALSimpleMenuState" name="A//V SETTINGS">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="FormatSelectionState" />
        <ActivationCriteria key="scrnCtrl" value="ActionsMenuScrnCtrlr" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU" />
        </DirectDestination>
        <DirectDestination name="ACTION BAR">
          <IrKey name="RETOUR" />
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
          <Item name="SUBTITLES" dictionaryKey="DIC_PROG_ACTION_SUBTITLE" destination="SUBTITLES SELECTION"/>        
        </Items>
      </Menu>
    </State>

    <!--ACTION BAR -> A/V SETTINGS -> SUBTITLES SELECTION-->
    <State  xsi:type="DALSimpleMenuState" name="SUBTITLES SELECTION">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="SubtitleSelectionState" />
        <ActivationCriteria key="scrnCtrl" value="ActionsMenuScrnCtrlr" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU" />
        </DirectDestination>
        <DirectDestination name="A//V SETTINGS">
          <IrKey name="RETOUR" />
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="UpDown" type="NonCircular" selectionIdentifier="title">
        <Items>
          <Item name="OFF" dictionaryKey="DIC_SETTINGS_OPTION_OFF" destination="LIVE"/>
          <Item name="DEUTSCH" dictionaryKey="DIC_SETTINGS_OPTION_OFF" destination="LIVE"/>
        </Items>
      </Menu>
    </State>
    
    <!--Add to-->
    <State name="CONFIRMATION">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="ConfirmationState" />
        <ActivationCriteria key="scrnCtrl" value="ActionsMenuScrnCtrlr" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="LIVE">
          <Delay time="1"/>
        </DirectDestination>
      </DirectDestinations>
    </State>


    <!--MAIN MENU-->
    <State xsi:type="DALSimpleMenuState" name="MAIN MENU" extraAnimationDuration="3">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="MainMenuTran" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="LIVE">
          <IrKey name="RETOUR" />
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="RightLeft" type="Circular" selectionIdentifier="title">
        <Items>
          <Item name="CHANNELS" dictionaryKey="DIC_MAIN_MENU_ON_NOW" destination="LIVE" />
          <Item name="NON EXISTING" dictionaryKey="" destination="" />
          <!--<Item name="SUGGESTED" dictionaryKey="SUGGESTED" isPopup="false" destination="" />-->
          <Item name="TV GUIDE" dictionaryKey="DIC_MAIN_MENU_GUIDE" destination="TV GUIDE FILTER" />

          <Item name="SEARCH" dictionaryKey="DIC_MAIN_MENU_SEARCH" isPopup="true" >
            <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
              <Items>
                <Item name="KEYWORD" dictionaryKey="DIC_MAIN_MENU_KEYWORD" destination="KEYWORD" />
                <Item name="MORE OPTIONS" dictionaryKey="DIC_MAIN_MENU_ADVANCED" destination="MORE OPTIONS" />
              </Items>
            </Menu>
          </Item>

          <Item name="TOOLBOX" dictionaryKey="DIC_MAIN_MENU_TOOLBOX" isPopup="true">
            <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
              <Items>
                <Item name="SETTINGS" dictionaryKey="DIC_MAIN_MENU_SETTINGS" destination="SETTINGS" />
                <Item name="CUSTOMER CARE" dictionaryKey="DIC_MAIN_MENU_UPC_CUSTOMER_CARE" destination="CUSTOMER CARE" />
              </Items>
            </Menu>
          </Item>
          <Item name="STORE" dictionaryKey="DIC_MAIN_MENU_STORE" destination="STORE ERROR" />
          <Item name="MY LIBRARY" dictionaryKey="DIC_MAIN_MENU_MY_LIB" destination="MY LIBRARY" />
        </Items>
      </Menu>
    </State>

    <!--MAIN MENU -> STORE -> STORE ERROR-->
    <State name="STORE ERROR">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="AuxAppState" />
        <ActivationCriteria key="scrnCtrl" value="StoreErrorScrnCtrlr" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU" />
        </DirectDestination>
      </DirectDestinations>
    </State>

    <!--MAIN MENU -> SEARCH -> KEYWORD-->
    <State name="KEYWORD">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="KeywordSearchState" />
        <ActivationCriteria key="scrnCtrl" value="KeywordSearch" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU" />
        </DirectDestination>
      </DirectDestinations>
    </State>

    <!-- MAIN MENU -> SEARCH -> MORE OPTIONS -->
    <State xsi:type="DALSimpleMenuState" name="MORE OPTIONS">
      <ActivationCriterias>
        <ActivationCriteria key="state" value=" AdvancedSearchState" />
        <ActivationCriteria key="scrnCtrl" value="AdvancedSearch" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU" />
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
          <Item name="KEYWORD" DictionaryKey="DIC_KEYWORD" destination=""/>
          <Item name="GENRE" dictionaryKey="DIC_ADV_SEARCH_CRITERIA_GENRE" destination=""/>
          <Item name="CHANNEL" dictionaryKey="DIC_ADV_SEARCH_CRITERIA_CHANNEL" destination="" />
          <Item name="DAY" dictionaryKey ="DIC_ADV_SEARCH_CRITERIA_DAY" destination="" />
        </Items>
      </Menu>
    </State>

    <!-- CUSTOMER CARE -->
    <State xsi:type="DALSimpleMenuState" name="CUSTOMER CARE">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="CCareFaqCategoryState" />
        <ActivationCriteria key="scrnCtrl" value="CCareFaqCategoryScrnCtrlr" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU" />
        </DirectDestination>
        <DirectDestination name="MAIN MENU">
          <IrKey name="RETOUR" />
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
          <Item name="HORIZON ASSISTANT" DictionaryKey="DIC_CUSTOMER_CARE_FAQ" destination=""/>
          <Item name="ACCOUNT ASSISTANT" dictionaryKey="DIC_BILL_ON_TV" destination=""/>
          <Item name="CONNECTION ASSISTANT" dictionaryKey="DIC_CONNECTION_TEST" destination="CONNECTION ASSISTANT" />
          <Item name="CONTACT US" dictionaryKey ="DIC_CONTACT_US" destination="CONTACT US" />
        </Items>
      </Menu>
    </State>


    <!-- CUSTOMER CARE -> CONTACT US -->
    <State xsi:type="DALSimpleMenuState" name="CONTACT US">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="CCareContactUsState" />
        <ActivationCriteria key="scrnCtrl" value="CCareContactUsCtrl" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU" />
        </DirectDestination>
        <DirectDestination name="CUSTOMER CARE">
          <IrKey name="RETOUR" />
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
          <Item name="HELP &amp; INFO" DictionaryKey="DIC_MORE_QA" destination=""/>
          <Item name="JOIN US" dictionaryKey="DIC_JOIN_US" destination=""/>
          <Item name="CALL US" dictionaryKey="DIC_CALL_US" destination="" />
          <Item name="MAIL US" dictionaryKey ="DIC_MAIL_US" destination="" />
          <Item name="CHAT WITH US" dictionaryKey ="DIC_CHAT_WITH_US" destination="" />
          <Item name="WRITE TO US" dictionaryKey ="DIC_WRITE_US" destination="" />
          <Item name="TWEET US" dictionaryKey ="DIC_TWEET_US" destination="" />
          <Item name="VISIT US" dictionaryKey ="DIC_VISIT_US" destination="" />
        </Items>
      </Menu>
    </State>


    <!-- CUSTOMER CARE ->  CONNECTION ASSISTANT-->
    <State xsi:type="DALSimpleMenuState" name="CONNECTION ASSISTANT">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="CCareTestingState" />
        <ActivationCriteria key="scrnCtrl" value="CCarePerformTestCtrl" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU" />
        </DirectDestination>
        <DirectDestination name="CUSTOMER CARE">
          <IrKey name="RETOUR" />
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="UpDown" type="NonCircular" selectionIdentifier="title">
        <Items>
          <Item name="YES" DictionaryKey="DIC_SETTINGS_OPTION_YES" destination=""/>
          <Item name="NO" dictionaryKey="DIC_SETTINGS_OPTION_NO" destination="CUSTOMER CARE"/>         
        </Items>
      </Menu>
    </State>


    <!--      SETTINGS          -->

    <!-- Settings - maim menu -->
    <State xsi:type="DALSimpleMenuState" name="SETTINGS">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="SettingsMenuState" />
        <ActivationCriteria key="scrnCtrl" value="SETTINGSScrnCtrlr" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU" />
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
          <Item name="HORIZON BOX" dictionaryKey="DIC_SETTINGS_BOX_SET_UP" destination="HORIZON BOX"/>
          <Item name="TELEVISION" dictionaryKey="DIC_SETTINGS_TV_SETTINGS" destination="TELEVISION"/>
          <Item name="PIN &amp; PARENTAL CONTROL" dictionaryKey="DIC_SETTINGS_PIN_AND_PC" destination="PIN &amp; PARENTAL CONTROL" />
          <Item name="RECORDINGS &amp; REMINDERS" dictionaryKey ="DIC_SETTINGS_DVR_AND_REMINDERS" destination="REC AND REM" />
          <Item name="PREFERENCES" dictionaryKey="DIC_SETTINGS_USER_PREF" destination="PREFERENCES" />
          <Item name="HOME NETWORK" dictionaryKey="DIC_SETTINGS_HOME_NETWORK" destination="" />
        </Items>
      </Menu>
    </State>

    <!-- Settings -> HORIZON BOX -->
    <State xsi:type="DALSimpleMenuState" name="HORIZON BOX">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="SettingsMenuState" />
        <ActivationCriteria key="scrnCtrl" value="HORIZON BOXScrnCtrlr" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU" />
        </DirectDestination>
        <DirectDestination name="SETTINGS">
          <IrKey name="RETOUR" />
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
          <Item name="POWER MANAGEMENT" dictionaryKey ="DIC_SETTINGS_POWER_MNGMNT" destination="" />
          <Item name="SOFTWARE" dictionaryKey ="DIC_BOX_INFORMATION" destination="" />
          <Item name="FACTORY RESET" dictionaryKey ="DIC_SETTINGS_FACTORY_RESET" destination="ENTER PIN" />
          <Item name="ADD REMOTE CONTROL" dictionaryKey ="DIC_SETTINGS_ADD_RC" destination="" />
          <Item name="FRONT PANEL BRIGHTNESS" dictionaryKey ="DIC_SETTING_FRONT_PANEL_BRIGHT" destination="" />
        </Items>
      </Menu>
    </State>

    <!-- Settings -> TELEVISION -->
    <State xsi:type="DALSimpleMenuState" name="TELEVISION">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="SettingsMenuState" />
        <ActivationCriteria key="scrnCtrl" value="TELEVISIONScrnCtrlr" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU" />
        </DirectDestination>
        <DirectDestination name="SETTINGS">
          <IrKey name="RETOUR" />
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
          <Item name="VIDEO SETTINGS" dictionaryKey ="DIC_SETTINGS_VIDEO_FORMAT" destination="VIDEO SETTINGS" />
          <Item name="AUDIO SETTINGS" dictionaryKey ="DIC_SETTINGS_AUDIO_FORMAT" destination="AUDIO SETTINGS" />
        </Items>
      </Menu>
    </State>

    <!-- Settings -> TELEVISION -> VIDEO SETTINGS -->
    <State xsi:type="DALSimpleMenuState" name="VIDEO SETTINGS">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="SettingsMenuState" />
        <ActivationCriteria key="scrnCtrl" value="VIDEO SETTINGSScrnCtrlr" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU" />
        </DirectDestination>
        <DirectDestination name="TELEVISION">
          <IrKey name="RETOUR" />
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
          <Item name="MAIN VIDEO CONNECTION" dictionaryKey ="DIC_SETTINGS_VIDEO_OUTPUT" destination="MAIN VIDEO CONNECTION" />
          <Item name="TV SET INFO" dictionaryKey ="DIC_SETTINGS_DIAGNOSTICS_TV" destination="TV SET INFO" />
          <Item name="HDMI RESOLUTION" dictionaryKey ="DIC_SETTINGS_HD_RESOLUTION" destination="HDMI RESOLUTION" />
          <Item name="4:3 VIDEO DISPLAY" dictionaryKey ="DIC_SETTINGS_TV_FORMAT" destination="4:3 VIDEO DISPLAY" />
        </Items>
      </Menu>
    </State>

    <!-- Settings -> TELEVISION -> VIDEO SETTINGS -> MAIN VIDEO CONNECTION -->
    <State xsi:type="DALSimpleMenuState" name="MAIN VIDEO CONNECTION">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="SettingsLeafState" />
        <ActivationCriteria key="scrnCtrl" value="MAIN VIDEO CONNECTIONScrnCtrlr" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU" />
        </DirectDestination>
        <DirectDestination name="VIDEO SETTINGS">
          <IrKey name="RETOUR" />
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
          <Item name="AUTOMATIC SELECTION" dictionaryKey ="DIC_SETTINGS_VIDEO_OUTPUT" destination="VIDEO SETTINGS" />
          <Item name="HDMI" dictionaryKey ="DIC_SETTINGS_DIAGNOSTICS_TV" destination="VIDEO SETTINGS" />
          <Item name="SCART" dictionaryKey ="DIC_SETTINGS_HD_RESOLUTION" destination="VIDEO SETTINGS" />
        </Items>
      </Menu>
    </State>

    <!--Settings -> TELEVISION -> VIDEO SETTINGS -> TV SET INFO->  -->
    <State name="TV SET INFO">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="SettingsLeafState" />
        <ActivationCriteria key="scrnCtrl" value="TV SET INFOScrnCtrlr" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU"/>
        </DirectDestination>
        <DirectDestination name="VIDEO SETTINGS">
          <IrKey name="RETOUR" />
        </DirectDestination>
      </DirectDestinations>
    </State>

    <!-- Settings -> TELEVISION -> VIDEO SETTINGS -> HDMI RESOLUTION -->
    <State xsi:type="DALSimpleMenuState" name="HDMI RESOLUTION">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="SettingsLeafState" />
        <ActivationCriteria key="scrnCtrl" value="HDMI RESOLUTIONScrnCtrlr" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU" />
        </DirectDestination>
        <DirectDestination name="VIDEO SETTINGS">
          <IrKey name="RETOUR" />
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
          <Item name="FOLLOW TV RESOLUTION" dictionaryKey ="DIC_SETTINGS_HD_FORMAT_TV_PREFERRED" destination="VIDEO SETTINGS" />
          <Item name="AUTOMATIC SELECTION" dictionaryKey ="DIC_VIDEO_OUTPUT_AUTO" destination="VIDEO SETTINGS" />
          <Item name="1080p" dictionaryKey ="DIC_SETTINGS_HD_FORMAT_1080P" destination="VIDEO SETTINGS" />
          <Item name="1080i" dictionaryKey ="DIC_SETTINGS_HD_FORMAT_1080I" destination="VIDEO SETTINGS" />
          <Item name="720p" dictionaryKey ="DIC_SETTINGS_HD_FORMAT_720P" destination="VIDEO SETTINGS" />
          <Item name="576p" dictionaryKey ="DIC_SETTINGS_HD_FORMAT_576P" destination="VIDEO SETTINGS" />
        </Items>
      </Menu>
    </State>

    <!-- Settings -> TELEVISION -> VIDEO SETTINGS -> 4:3 VIDEO DISPLAY -->
    <State xsi:type="DALSimpleMenuState" name="4:3 VIDEO DISPLAY">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="SettingsLeafState" />
        <ActivationCriteria key="scrnCtrl" value="4:3 VIDEO DISPLAYScrnCtrlr" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU" />
        </DirectDestination>
        <DirectDestination name="VIDEO SETTINGS">
          <IrKey name="RETOUR" />
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
          <Item name="PILLARBOX" dictionaryKey ="DIC_SETTINGS_TV_FORMAT_PILLAR_BOX" destination="VIDEO SETTINGS" />
          <Item name="FULLSCREEN (ZOOM)" dictionaryKey ="DIC_SETTINGS_TV_FORMAT_ZOOM" destination="VIDEO SETTINGS" />
          <Item name="FULLSCREEN (STRETCH)" dictionaryKey ="DIC_SETTINGS_TV_FORMAT_FULL_SCREEN" destination="VIDEO SETTINGS" />
        </Items>
      </Menu>
    </State>

    <!-- Settings -> TELEVISION -> AUDIO SETTINGS -->
    <State xsi:type="DALSimpleMenuState" name="AUDIO SETTINGS">
      <ActivationCriterias>
        <ActivationCriteria key="state" value="SettingsMenuState" />
        <ActivationCriteria key="scrnCtrl" value="AUDIO SETTINGSScrnCtrlr" />
      </ActivationCriterias>
      <DirectDestinations>
        <DirectDestination name="MAIN MENU">
          <IrKey name="MENU" />
        </DirectDestination>
        <DirectDestination name="TELEVISION">
          <IrKey name="RETOUR" />
        </DirectDestination>
      </DirectDestinations>
      <Menu layout="UpDown" type="Circular" selectionIdentifier="title">
        <Items>
          <Item name="SCART OUTPUT" dictionaryKey ="DIC_ANA_AUDIO_SCART" destination="SCART OUTPUT" />
          <Item name="HDMI OUTPUT" dictionaryKey ="DIC_SETTINGS_HDMI_AUDIO_OUTPUT" destination="HDMI OUTPUT" />
          <Item name="S//PDIF OUTPUT" dictionaryKey ="DIC_SETTINGS_SPDIF_AUDIO_OUTPUT" destination="S//PDIF OUTPUT" />
          <Item name="DOLBY (AC3) OUTPUT" dictionaryKey ="DIC_DOLBY_OUTPUT" destination="DOLBY (AC3) OUTPUT" />
          <Item name="S//PDIF AUDIO DELAY" dictionaryKey ="DIC_SETTINGS_SPDIF_AUDIO_DELAY" destination="S//PDIF AUDIO DELAY" />
          <Item name="HDMI AUDIO DELAY" dictionaryKey ="DIC_HDMI_AUDIO_DELAY" destination="HDMI AUDIO DELAY" />
          <Item name="RESET LANGUAGE SETTINGS" dictionaryKey ="DIC_SETTINGS_RESET_SOUNDTRACK_SETTINGS" destination="RESET LANGUAGE SETTINGS" />
        </Items>
      </Menu>
    </State>

    <!-- Settings -> TELEVISION -> AUDIO SETTINGS -> SCART OUTPUT -->
    <State xsi:type="DALSimpleMenuState" name="SCART OUTPUT">
      <ActivationCriterias>